import sqlite3

connection = sqlite3.connect("fast_food.db")

cursor = connection.cursor()

tables = cursor.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")

for table in tables.fetchall():
    cursor.execute("UPDATE " + table[0] + " SET is_drink = CASE WHEN item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '% Ale%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Coke%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Sundae%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Milk%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Juice%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Tea%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Beer%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Coffee%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Mocha%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Pepsi%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Cola%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Palmer%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Mountain Dew%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Lemonade%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Dr %' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Hot Chocolate%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Mist%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Sprite%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Water%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Fanta%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE 'Smoothie' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Hi_C %' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Brew%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Moolatt %' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Blizzard%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Malt%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Shake%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Macchiato%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Caffe %' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Cappuccino%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Espresso%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '% Latte%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Acai%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Evolution %' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Frappuccino%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Drink%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '% Creme%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Blonde %' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Decaf %' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Dark Roast%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Place Roast%' OR item_name COLLATE SQL_Latin1_General_CP1_CI_AS LIKE '%Slurpee%' THEN 1 ELSE 0 END")
    connection.commit()